### ISSUE TITLE
android:Unsupported scheme

### ISSUE THREAD

**Issue by Link-Kou** [Vydia/react-native-background-upload#115]
android 
https://github.com/ivpusic/react-native-image-crop-picker

Error: Unsupported scheme: file:///data/user/0/com.zhitaoapp/cache/react-native-image-crop-picker/61609ee7-3df2-495d-8725-760308c49031.jpg
    at createErrorFromErrorData (blob:http://localhost:8081/c7a3c964-e297-4c09-ab75-7eec73171960:2019:17)
    at blob:http://localhost:8081/c7a3c964-e297-4c09-ab75-7eec73171960:1971:27
    at MessageQueue.__invokeCallback (blob:http://localhost:8081/c7a3c964-e297-4c09-ab75-7eec73171960:2522:18)
    at blob:http://localhost:8081/c7a3c964-e297-4c09-ab75-7eec73171960:2269:18
    at MessageQueue.__guard (blob:http://localhost:8081/c7a3c964-e297-4c09-ab75-7eec73171960:2426:13)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:http://localhost:8081/c7a3c964-e297-4c09-ab75-7eec73171960:2268:14)
    at http://localhost:8081/debugger-ui/debuggerWorker.js:72:58

**Comment by fannaoshaoxiang** [comment]
Success:

Platform.select({
         ios: () => 'file://' + image.path,
         android: () => image.path.replace('file://', '')
})()

**Comment by DanthonyPabon** [comment]
not working for me 

I did this  file.replace("file://", "");

field: "uploaded_media"
files: "/data/user/0/com.picnow/cache/1549916302744.JPEG"
type: "multipart"
url: "http://192.168.0.21:3000/upload_multipart"

```
Error: null
Error: null
    at createErrorFromErrorData (blob:http://localhost:8081/1fee32fc-ab77-4062-8fa9-357c0c23b0d4:8295:17)
    at blob:http://localhost:8081/1fee32fc-ab77-4062-8fa9-357c0c23b0d4:8247:27
    at MessageQueue.__invokeCallback (blob:http://localhost:8081/1fee32fc-ab77-4062-8fa9-357c0c23b0d4:8777:18)
    at blob:http://localhost:8081/1fee32fc-ab77-4062-8fa9-357c0c23b0d4:8524:18
    at MessageQueue.__guard (blob:http://localhost:8081/1fee32fc-ab77-4062-8fa9-357c0c23b0d4:8681:13)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:http://localhost:8081/1fee32fc-ab77-4062-8fa9-357c0c23b0d4:8523:14)
    at http://localhost:8081/debugger-ui/debuggerWorker.js:72:58
```

**Comment by DanthonyPabon** [comment]
My Example: 


```
let file = this.state.file;
if (Platform.OS == "android") {
  file = this.state.file.replace("file://", "");
}
const options = {
  url: "http://192.168.0.21:3000/upload_multipart",
  path: file,
  method: "POST",
  field: "uploaded_media",
  type: "multipart",
  headers: {
    "content-type": "application/octet-stream", // Customize content-type
    "my-custom-header": "s3headervalueorwhateveryouneed"
  },
  // Below are options only supported on Android
  notification: {
    enabled: true
  }
};
Upload.startUpload(options)
  .then(uploadId => {
    console.log("Upload started");
    Upload.addListener("progress", uploadId, data => {
      console.log(`Progress: ${data.progress}%`);
    });
    Upload.addListener("error", uploadId, data => {
      console.log(`Error: ${data.error}%`);
    });
    Upload.addListener("cancelled", uploadId, data => {
      console.log(`Cancelled!`);
    });
    Upload.addListener("completed", uploadId, data => {
      // data includes responseCode: number and responseBody: Object
      console.log("Completed!");
    });
  })
  .catch(err => {
    console.log("Upload error!", err);
  });
```

**Comment by iJimmyWei** [comment]
The examples given should be updated to reflect this with @fannaoshaoxiang's fix as a temporary bandage.

The root cause is directly due to https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/schemehandlers/SchemeHandlerFactory.java `    private SchemeHandlerFactory() {
        handlers.put("/", FileSchemeHandler.class);
        handlers.put("content://", ContentSchemeHandler.class);
    }`

**Comment by hayridurmaz** [comment]
> Success:
> 
> Platform.select({
> ios: () => 'file://' + image.path,
> android: () => image.path.replace('file://', '')
> })()

it is the opposite working for me? what the hell?
