### ISSUE TITLE
Android crash when turning off WiFi during upload (product flavor issue?)

### ISSUE THREAD

**Issue by projuljustin** [Vydia/react-native-background-upload#251]
Hey there, I seem to be having an issue when turning off WiFi during an upload. The app crashes and I get this error:

2021-05-03 15:06:30.092 11885-11885/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp.webview, PID: 11885
    java.lang.RuntimeException: Unable to create service net.gotev.uploadservice.UploadService: java.lang.IllegalArgumentException: You have to set namespace to your app package name (context.packageName) in your Application subclass
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4180)
        at android.app.ActivityThread.access$1600(ActivityThread.java:232)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7617)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
     Caused by: java.lang.IllegalArgumentException: You have to set namespace to your app package name (context.packageName) in your Application subclass
        at net.gotev.uploadservice.UploadServiceConfig.getNamespace(UploadServiceConfig.kt:74)
        at net.gotev.uploadservice.UploadServiceConfig.getBroadcastNotificationAction(UploadServiceConfig.kt:234)
        at net.gotev.uploadservice.UploadServiceConfig.getBroadcastNotificationActionIntentFilter(UploadServiceConfig.kt:248)
        at net.gotev.uploadservice.observer.request.NotificationActionsObserver.register(NotificationActionsObserver.kt:31)
        at net.gotev.uploadservice.UploadService.onCreate(UploadService.kt:194)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4168)
        at android.app.ActivityThread.access$1600(ActivityThread.java:232) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:241) 
        at android.app.ActivityThread.main(ActivityThread.java:7617) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941) 
        
I don't seem to get this issue when running my dev or tst app (com.myapp.webviewdev or com.myapp.webviewtest)

`              return new Promise((resolve, reject) => {
                Upload.startUpload(options).then((uploadId) => {
                  this.props.log('processQueue', `${jobTypes.uploadFileAndBlob} upload started for ${image.responseFileName}`);
                  this.updateUploadStatus(image.responseFileName, 'uploading');
                  Upload.addListener('progress', uploadId, (uploadData) => {
                  })
                  Upload.addListener('error', uploadId, (uploadData) => {
                    this.props.log('processQueue', `${jobTypes.uploadFileAndBlob} upload error for ${image.responseFileName}`)
                    this.updateUploadStatus(image.responseFileName, 'error', uploadData.responseCode);
                    throw new Error(`${jobTypes.uploadFileAndBlob} upload error for ${image.responseFileName}`);
                  })
                  Upload.addListener('cancelled', uploadId, (uploadData) => {
                    this.props.log('processQueue', `${jobTypes.uploadFileAndBlob} upload cancelled for ${image.responseFileName}`)
                    this.updateUploadStatus(image.responseFileName, 'cancelled');
                    throw new Error(`${jobTypes.uploadFileAndBlob} upload cancelled for ${image.responseFileName}`);
                  })
                  Upload.addListener('completed', uploadId, (uploadData) => {
                    if (uploadData.responseCode === 403) {
                      this.props.log('processQueue', `${jobTypes.uploadFileAndBlob} upload failed with 403 for ${image.responseFileName}`);
                      this.updateUploadStatus(image.responseFileName, 'error', uploadData.responseCode);
                      throw new Error(`${jobTypes.uploadFileAndBlob} upload failed with 403 for ${image.responseFileName}`);
                    } else if (uploadData.responseCode === 201) {
                      this.props.log('processQueue', `${jobTypes.uploadFileAndBlob} upload success for ${image.responseFileName}`);
                      this.updateUploadStatus(image.responseFileName, 'uploaded');
                      let removeImagePayload = {
                        fileName: image.responseFileName,
                        filePath: image.filePath
                      };
                      this.createNewJob(jobTypes.removeImage, removeImagePayload);
                      let updatePhotoUploadData = {
                        action: 'add_uploaded'
                      };
                      this.props.updatePhotoUpload(updatePhotoUploadData);
                      resolve();
                    } else {
                      this.props.log('processQueue', `${jobTypes.uploadFileAndBlob} upload finished with unknown response code of ${uploadData.responseCode} for ${image.responseFileName}`);
                      this.updateUploadStatus(image.responseFileName, 'error', uploadData.responseCode);
                      throw new Error(`${jobTypes.uploadFileAndBlob} upload finished with unknown response code of ${uploadData.responseCode} for ${image.responseFileName}`);
                    }
                  })
                }).catch((error) => {
                  this.props.log('processQueue', `${jobTypes.uploadFileAndBlob} upload error: ${error?.message}`);
                  reject();
                  throw new Error(`${jobTypes.uploadFileAndBlob} upload error: ${error?.message}`);
                })
              });`

**Comment by lewisd1996** [comment]
@projuljustin Hi, did you ever find a solution to this?

**Comment by Jsxde** [comment]
I have the same error, wondering too if anyone has a solution

**Comment by aidinb** [comment]
I have the same issue

**Comment by scremona-navico** [comment]
Add this to your build.gradle:
android {
    // Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
        namespace "com.vydia.RNUploader"
    } else {
        // print
        println "DEPRECATION WARNING: The `namespace` property is not available in your version of AGP. Please upgrade to AGP 4.2+."
    }
...

then you'll probably need this fix too:
https://github.com/Vydia/react-native-background-upload/issues/343
